In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score

import matplotlib.pyplot as plt

import mutiple_LinearRegression as MLR

In [11]:
df = pd.read_csv("infor_weather.csv")

In [12]:
# Splitting the DataFrame into training and testing sets with a 70-30 split ratio
# and specifying a random seed for reproducibility
train, test = train_test_split(df, test_size = 0.3, random_state=40)

# Split the data again to simplify the problem with curr practice
x_train = train.iloc[:, :-1] # All columns except the last one
y_train = train.iloc[:, -1]  # The last column

x_test = test.iloc[:, :-1]
y_test = test.iloc[:, -1]


In [13]:
# Create Linear Regression model
model = LinearRegression()

# Fit model to data
model.fit(x_train, y_train)

# Prediction
y_pred = model.predict(x_test)
y_pred = y_pred.reshape(-1, 1)
print(y_pred)

[[194.82319475]
 [132.35714487]
 [223.88401133]
 ...
 [ 84.01346063]
 [163.62365736]
 [151.37446613]]


In [14]:
"""Manual"""
# Handle arguments
x_trainM = x_train.values
y_trainM = y_train.values

x_testM = x_test.values
y_testM = y_test.values

model_Manual = MLR.LinearRegression()

# Compute coeficient
model_Manual.fit(x_train, y_train)

# Predicttion
y_predManual = model_Manual.predict(x_testM)
y_predManual = y_predManual.reshape(-1, 1)
print(y_predManual)

[[194.82319475]
 [132.35714487]
 [223.88401134]
 ...
 [ 84.01346063]
 [163.62365736]
 [151.37446614]]


In [15]:
print(y_pred - y_predManual)

[[-1.99241867e-09]
 [-1.91658955e-09]
 [-1.94970085e-09]
 ...
 [-2.03938555e-09]
 [-2.58071964e-09]
 [-2.21791652e-09]]


In [19]:

# Assuming y_true contains the true values and y_pred contains the predicted values
r_squared = r2_score(y_test.values.reshape(-1, 1), y_predManual)
r_squared_ = r2_score(y_test.values.reshape(-1, 1), y_pred)

# Print the R-squared value
print("R-squared:", r_squared)
print("R-squared:", r_squared_)

R-squared: 0.4255921846491679
R-squared: 0.4255921846500029
